name             'play_framework'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures play_framework'
long_description 'Installs/Configures play_framework'
version          '0.1.36'
depends 'apt', '~> 2.6.1'
